### ISSUE TITLE
Replicas count set is string instead of number

### ISSUE THREAD

**Issue by vividvilla** [mr-karan/kubekutr#11]
Config file generated via `init` command sets replica count in string instead of a number. Here is a sample generated file

```yaml
workloads:
- name: xxxxx
  deployments:
  - name: xxxxxxx
    replicas: "2"
    containers:
    - createService: true
      name: app
      image: xxxx
      envSecret: ""
      envVars: []
      container: ""
      ports:
      - port: "8000"
      command: ""
      args: ""
      volumeMounts: []
      cpuRequests: 250m
      memoryRequests: 128Mi
      cpuLimits: 500m
      memoryLimits: 256Mi
      readinessPort: "8000"
      readinessPath: /
      livenessPort: "8000"
      livenessPath: /
    labels: []
    volumes: []
  services: []
  ingresses: []
  statefulsets: []
```
