### ISSUE TITLE
`mi` or `Mi` for quantity's suffix ?

### ISSUE THREAD

**Issue by josejibin** [mr-karan/kubekutr#12]
Not sure this is a bug or not.  When we generate a default config, using the command `kubekutr init --default`, it generates config with `memoryLimits: 1500mi` and `memoryRequests: 750mi`.
Shouldn't suffix be `Mi` instead of `mi`?

I have added a default config generated using `kubekutr` below.
```
workloads:
  - name: app
    deployments:
      - name: app
        replicas: 3
        labels:
          - name: 'service: app'
          - name: 'tier: frontend'
        containers:
          - name: app
            createService: true
            image: 'myapp:latest'
            envSecret: myapp
            ports:
            - name: app-port
              port: 3000
            command: '["./myapp"]'
            args: '["--config", "--hello"]'
            cpuLimits: 800m
            memoryLimits: 1500mi
            cpuRequests: 400m
            memoryRequests: 750mi
            readinessPort: 3000
            readinessPath: /api/readiness
            livenessPort: 3000
            livenessPath: /api/liveness
            envVars:
              - name: hello
                value: iamsecret
            volumeMounts:
              - name: config-dir
                mountPath: /etc/config
                subPath: config.toml
        volumes:
          - name: config-dir
    services:
      - name: app
        type: NodePort
        headless: true
        ports:
          - name: app-port
            targetPort: 8000
            port: app-port
            protocol: UDP
          - name: cache-port
            targetPort: 7000
            port: 9000
        labels:
          - name: 'service: app'
        selectors:
          - name: 'tier: frontend'
    ingresses:
      - name: app
        annotations:
          - name: 'alb.ingress.kubernetes.io/healthy-threshold-count: "2"'
        ingressPaths:
          - path: /503
            service: app
            port: use-annotation
  - name: second-app
    statefulsets:
      - name: db
        serviceName: db-headless
        labels:
          - name: 'service: postgres'
          - name: 'tier: db'
        containers:
          - name: postgres
            image: 'postgres:latest'
            envSecret: postgres
            ports:
            - name: app-port
              port: 3000
            envVars:
              - name: POSTGRES_DB
                value: sample
            volumeMounts:
              - name: db-dir
                mount: /var/lib/postgres
            cpuLimits: 800m
            memoryLimits: 1500mi
            cpuRequests: 400m
            memoryRequests: 750mi
        volumes:
          - name: db-dir
```
