### ISSUE TITLE
Feature Request: Option to render to app-specific directories

### ISSUE THREAD

**Issue by nabadger** [mr-karan/kubekutr#2]
At the moment `kubekutr` renders by resource-type (i.e. all deployments end up in a `deployments` directory).

It might be nice to have the option to split these by application.

i.e render to:

```
./app1/deployment.yaml
./app1/service.yaml
...
./app2/deployment.yaml
./app2/service.yaml
```
I'm not sure whether this would require a re-structuring of the config, such that all application resources can share the `name` value. At the moment all config definitions seem independent from one another.

i.e. another config file could look like:

```yaml
applications:
- name: app1
  deployments: 
  ...
  ingresses:
- name: app2  
  deployments:
  ...
```
Generally speaking, this might help from a development point of view, since it would allow you to focus on all resources for the specific application in question (i.e. bundle them all under the same directory).

**Comment by mr-karan** [comment]
Yeah this kind of structure probably makes more sense from a UX perspective. Will add in next release :)

**Comment by mr-karan** [comment]
@nabadger I've a rough implementation ready, but how would you like to address the issue where one app can have multiple deployments/ingress resources? Would a format like `{name}-{resourceType}` be fine?

For example, for the given config
```
workloads:
  - name: app
    deployments:
      - name: app
        ...
      - name: queue
        ...
    services:
      - name: app
        ...
```

How structure should look like?

```
myapp/base/app/app-deployment.yml
myapp/base/app/queue-deployment.yml
myapp/base/app/app-service.yml
```

I'd like to think of config as a "workload" (set of resources like deployments, services, ingresses required to run your application fully) and in that case multiple resource types are definitely possible. So we need to prefix them with the name, to make it unique. This is what I could think of, if you've better ideas please let me know :smile:
